GOOGLE_SHEET_URL="https://docs.google.com/spreadsheets/d/1HoOHdKoogz_Pyl2urAcjpQraeIgJvbzY846Mm9hzEWY/edit?usp=sharing"



[users]

admin="admin123"

officer="officer123"

viewer="viewer123"



[roles]

admin="Administrator"

officer="Data Officer"

viewer="Viewer"
